//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xam.Applications.GradientEditor.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xam.Applications.GradientEditor.Controls.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current stop must be between {0} and {1}, inclusive.
        /// </summary>
        public static string ArgumentException_CurrentEditStop {
            get {
                return ResourceManager.GetString("ArgumentException_CurrentEditStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum stops must be greater than minimim stops.
        /// </summary>
        public static string ArgumentException_MaximumStops {
            get {
                return ResourceManager.GetString("ArgumentException_MaximumStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum stops must be at least 2.
        /// </summary>
        public static string ArgumentException_MinimumStops {
            get {
                return ResourceManager.GetString("ArgumentException_MinimumStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected stop count must be betwwen MinStops and MaxStops, inclusive.
        /// </summary>
        public static string ArgumentException_SelectedStopsCount {
            get {
                return ResourceManager.GetString("ArgumentException_SelectedStopsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift gradient colors to the left.
        /// </summary>
        public static string CommandDescriptionShiftColorsLeft {
            get {
                return ResourceManager.GetString("CommandDescriptionShiftColorsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift gradient colors to the right.
        /// </summary>
        public static string CommandDescriptionShiftColorsRight {
            get {
                return ResourceManager.GetString("CommandDescriptionShiftColorsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display stop dividers.
        /// </summary>
        public static string Label_DisplayStopDividers {
            get {
                return ResourceManager.GetString("Label_DisplayStopDividers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point X.
        /// </summary>
        public static string Label_EndPointX {
            get {
                return ResourceManager.GetString("Label_EndPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point Y.
        /// </summary>
        public static string Label_EndPointY {
            get {
                return ResourceManager.GetString("Label_EndPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point X.
        /// </summary>
        public static string Label_StartPointX {
            get {
                return ResourceManager.GetString("Label_StartPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point Y.
        /// </summary>
        public static string Label_StartPointY {
            get {
                return ResourceManager.GetString("Label_StartPointY", resourceCulture);
            }
        }
    }
}
